---
- name: Create peers_history systemd service
  template:
    src: "{{ peers_history_systemd_template }}"
    dest: "{{ peers_history_systemd_dir }}/peers-history.service"
    owner: "root"
    group: "root"
  become: true
  when: ( peers_history_managed_service ) and
    ( ansible_os_family != "Darwin" )
  register: systemd_file

- name: Set updated optionally to trigger a systemd restart at the end
  set_fact:
    peers_history_state_updates: "{{ peers_history_state_updates + ['peers_history.systemd_file'] }}"
  when: systemd_file is changed

- name: Reload systemd to reread configs
  systemd:
    daemon_reload: yes
  become: true
  when: systemd_file is changed

- name: Enable and start peers_history service
  systemd:
    name: peers-history
    state: "{{ peers_history_systemd_state }}"
    enabled: true
  become: true
  when: ( peers_history_state_updates|length > 0 ) and
    ( peers_history_managed_service ) and
    ( ansible_os_family != "Darwin" )
